name: ted_intelligence
version: "1.0.0"
profile: ted_intelligence

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ted_intelligence:
    bronze:
      +schema: ted
      +materialized: view
      +tags: ["bronze"]
    silver:
      +schema: ted
      +materialized: table
      +tags: ["silver"]
    gold:
      +schema: ted
      +materialized: table
      +tags: ["gold"]