ted_intelligence:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: procurement
      schema: ted
      host: "{{ env_var('DATABRICKS_HOST') | replace('https://', '') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4